CREATE TABLE Clientes
(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(70) NOT NULL,
CPF VARCHAR (11) NOT NULL,
RG VARCHAR (15) NOT NULL,
DATA_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
DATA_MENSALISTA_FINAL AS DATEADD(DAY, 30, DATA_CADASTRO),
ATIVO BIT DEFAULT 1 NOT NULL,
)

INSERT INTO Clientes(NOME, CPF, RG) VALUES
(
'JHON', '08222222222', '5555568'
)

CREATE TABLE Telefones
(
ID INT IDENTITY PRIMARY KEY,
CLIENTE_ID INT NOT NULL,
FOREIGN KEY (CLIENTE_ID) REFERENCES Clientes(ID),
NUMERO VARCHAR (20) NOT NULL,
)

CREATE TABLE Veiculos
(
ID INT IDENTITY PRIMARY KEY,
TIPO_VEICULO INT ,
MODELO VARCHAR (30) NOT NULL,
COR INT NOT NULL,
)

CREATE TABLE Registros
(
ID_REGISTRO INT IDENTITY PRIMARY KEY,
ID_VEICULO INT NOT NULL,
ID_CLIENTE INT NULL
FOREIGN KEY (ID_VEICULO) REFERENCES Veiculos(ID),
FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID),
UNIQUE(ID_VEICULO, ID_CLIENTE),
)

CREATE TABLE Vagas
(
ID INT IDENTITY PRIMARY KEY,
SETOR_VAGA VARCHAR(10) NOT NULL,
TIPO_VAGA INT DEFAULT 0 NOT NULL,
OCUPADA BIT DEFAULT 0 NOT NULL,
VALOR_USO FLOAT(10) NOT NULL,
ULTIMOUSO INT NULL,
FOREIGN KEY (ULTIMOUSO) REFERENCES Registros(ID_REGISTRO),
)

CREATE TABLE Movimentacoes
(
ID INT IDENTITY PRIMARY KEY,
REGISTRO_USO INT NOT NULL,
FOREIGN KEY (REGISTRO_USO) REFERENCES Registros(ID_REGISTRO),
DATA_ENTRADA DATETIME DEFAULT GETDATE() NOT NULL,
DATA_SAIDA DATETIME NULL,
VALOR_TOTAL FLOAT NULL,
)



